### ISSUE TITLE
Add link to discord to website

### ISSUE THREAD

**Issue by eduxstad** [ephs/ephs.github.io#3]
We should probably link to discord from the website. Not sure exactly how we should do it though. Do we want an embedded iframe or just a link?

**Comment by AlecDusheck** [comment]
I think a link would honestly look cleaner than a embed of our Discord server. 

However, I feel we also need to add alternate contact info. Possibly an email as well?

**Comment by andrewgazelka** [comment]
Also, should we have discord.ephs.club redirect to our Discord?

**Comment by AlecDusheck** [comment]
Yep.

**Comment by andrewgazelka** [comment]
Do you like that better than `ephs.club/discord`?

**Comment by AlecDusheck** [comment]
Honestly either one works. I feel that the [ephs.club/discord](https://ephs.club/discord) might be better for the long-term. Especially if we are going to be changing sub-domains around later on.

**Comment by andrewgazelka** [comment]
Alright. I personally think [ephs.club/discord](url) looks better as well. To support this we will need to either:

1. Use a client-side redirect (jank)
2. Host on a VPS/dedi and use a 301 redirect. I've got plenty to spare if we want to go this route.

**Comment by AlecDusheck** [comment]
I feel that transferring the entire site to a VPS would be best. Maybe if we're planning to go that route we should move away from this whole the whole Jekyll and make something else?

**Comment by andrewgazelka** [comment]
I'm pretty sure the Jekyll plugin just client-side redirects. I think it might be easier to just move onto a VPS anyway. More freedom and it would also be fun to setup.

**Comment by AlecDusheck** [comment]
Yep, [your right](https://github.com/jekyll/jekyll-redirect-from/blob/master/lib/jekyll-redirect-from/redirect_page.rb).

**Comment by AlecDusheck** [comment]
Merging this issue into [here](https://github.com/ephs/ephs.github.io/issues/4).
