### ISSUE TITLE
Remove github theme dependencies

### ISSUE THREAD

**Issue by eduxstad** [ephs/ephs.github.io#6]
In preparation for moving the site off of github.io (#4), we need to remove the dependencies on the github Jekyll theme and provide them ourselves. It's unlikely that we will complete a full redesign before the transition, so this would act as a stopgap in the meantime.

**Comment by AlecDusheck** [comment]
We have two options:

1. Just take the CSS stylesheets over and use NGINX
2. Install Jekyll on the server and host the site that way

**Comment by andrewgazelka** [comment]
I agree. I don't think we need Jekyll. In the future, we probably won't be using it anyway (I think).

**Comment by AlecDusheck** [comment]
Ok, when I get some time I'll copy over the site. If any of you want to do so feel free.

**Comment by eduxstad** [comment]
I have removed the dependencies on github.io themes.
