### ISSUE TITLE
Move ephs.github.io off of github.io

### ISSUE THREAD

**Issue by eduxstad** [ephs/ephs.github.io#7]
We should be ready to move the site off github.io and host it ourselves. Andrew will need to set this up or give access to other people access to do this.

**Comment by AlecDusheck** [comment]
I’ve got access and can do when I get home. However, Andrew will need to remap the domain name.

**Comment by andrewgazelka** [comment]
I will remap the domain right when it is finished.

**Comment by AlecDusheck** [comment]
Can someone update line #2 on the default.html file?

I’m on my phone and can’t do it.

**Comment by eduxstad** [comment]
fixed line 2

**Comment by eduxstad** [comment]
Done!
